In [3]:
#array operations
import numpy as np 
#1.arithmetic operation-the size of arrays should be the same


In [4]:
a1=np.array([1,2,3,4])


In [5]:
a2=np.array([5,6,7,8])

In [6]:
a1+a2

array([ 6,  8, 10, 12])

In [7]:
a1*a2

array([ 5, 12, 21, 32])

In [8]:
a1**a2

array([    1,    64,  2187, 65536])

In [9]:
a1//a2

array([0, 0, 0, 0])

In [10]:
a1-a2

array([-4, -4, -4, -4])

In [11]:
#2.Broadcasting - this concept can be used when you want to add a single element to all the elements of an array
a1+10


array([11, 12, 13, 14])

In [13]:
#3. deep and shallow copy
#deep copy-the copy and original are separate and changes in the copy do not reflect in the original
#because the sliced portion takes different location
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
slice=a[0:5]
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [18]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
#shallow copy-changes refelct in the original array
b=a
b[0]=99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
a#changes refelct in a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [23]:
#but if you dont want this to happen simply use the copy function
b=a.copy()

In [24]:
b[0]=11
b

array([11,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
a#unaffected

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
#4.matrix operation
#a. multiplication
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])




In [ ]:
A@B#or np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [31]:
#b.transpose
A.T

array([[1, 3],
       [2, 4]])

In [32]:
#5.advanced array manipulation
#a.stacking-horizontal,vertical,colummn
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [33]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [37]:
#b.splitting-horizontal,vertiical
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [39]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]