In [6]:
import numpy as np
#array indexing and slicing
#1.vectors
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[6]

np.int64(7)

In [5]:
#slicing-removing a part: default start value=0, default end value=1
n=arr[1:11:2]
n

array([ 2,  4,  6,  8, 10])

In [7]:
#2.matrices
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [8]:
#to print a row, supposedly first
arr[1]

array([ 6,  7,  8,  9, 10])

In [9]:
#to print an element, supposedly 7
arr[1,1]

np.int64(7)

In [11]:
#to print a column,supposedly first
arr[:,1]

array([ 2,  7, 12, 17, 22, 27])

In [13]:
#to print 2,3,7,8
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [18]:
#3.boolean indexing
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [19]:
#to print even number
bool_idx=arr%2==0
bool_idx

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [20]:
#if i want the even values
arr=arr[bool_idx]
arr

array([12, 14, 16, 18, 20])