In [1]:
import numpy as np

In [2]:
#1. prove whether it is a valid sudoku
s=np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],
    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],
    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]])

In [5]:
b=np.sum(s,axis=1)
for i in b:
    if i!=45:
        print("sudoku is not valid")
        break
else:
    print("sudoku is currently valid for rows")

sudoku is currently valid for rows


In [7]:
c=np.sum(s,axis=0)
for i in c:
    if i!=45:
        print("sudoku is not valid")
        break
else:
    print("sudoku is currently valid for columns")

sudoku is currently valid for columns


In [18]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n=s[i:i+3,j:j+3]
        print(n.sum())
        

45
45
45
45
45
45
45
45
45


In [19]:

#since the sum of each row amd sum of each column=45, and after slicing it into 3*3 matrix,
#the sum of each of the sliced matrix=45,therefore the sudoku is valud

In [20]:
#2
import numpy as np

In [21]:
#columns: age,math marks,science marks
data=np.array([
    [18,85,78], #student 1
    [19,92,88], #student 2
    [17,76,95], #student 3
    [18,65,70], #student 4
    [20,90,85]]) #student 5

In [23]:
#get the shape of matrix
data.shape

(5, 3)

In [28]:
#find the average age of students
d=data[0:5,0:1]
d

array([[18],
       [19],
       [17],
       [18],
       [20]])

In [33]:
n=d.mean()
n

np.float64(18.4)

In [35]:
#extract math marks of all students
f=data[0:5,1:2]
f

array([[85],
       [92],
       [76],
       [65],
       [90]])

In [36]:
#find the highest science marks
g=data[0:5,2:3]
g

array([[78],
       [88],
       [95],
       [70],
       [85]])

In [39]:
high=g.max()
high

np.int64(95)

In [41]:
#get details of student who scored more than 90 in maths
data[data[:,1]>90]

array([[19, 92, 88]])

In [43]:
#increase math marks of all students by 5
sum=data[:,1]+5
sum

array([90, 97, 81, 70, 95])

In [44]:
#find how many students are younger than 19
len(data[data[:,0]<19])

3

In [51]:
#calculate average marks in each subject(column wise mean)
np.mean(data[:,1:3],axis=0)

array([81.6, 83.2])

In [54]:
#get data of students who scored at last 80 in both subjects
data[(data[:,1])>=80 & (data[:,2]>=80)]



array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [55]:
#replace all science marks<75 with 0
data[:,2][data[:,2]<75]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])