In [ ]:
#numpy arrays
import numpy as np

In [ ]:
#1. basic array creation
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
#take a list with differesnt data types and pass it to an array, all the datatypes will
#change into unicodes
a=[1,2,"hello"]
a

[1, 2, 'hello']

In [ ]:
arr=np.array(a)
arr
#there wont be any error, but all of them get converted into string

array(['1', '2', 'hello'], dtype='<U21')

In [ ]:
#list does not support matrix
l=[[1,2],[3,4]]
l

[[1, 2], [3, 4]]

In [ ]:
arr=np.array(l)#array supports it
arr

array([[1, 2],
       [3, 4]])

In [ ]:
#2. array generation function
#to generate use np.arange // works as a range function.
arr=np.arange(1,11)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [ ]:
#to generate zeros
arr=np.zeros(6)#//this is a vector but what if i want it to be a matrix?
arr


array([0., 0., 0., 0., 0., 0.])

In [ ]:
ar=np.zeros((6,4))
ar

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr=np.ones((2,2))
arr

array([[1., 1.],
       [1., 1.]])

In [ ]:
#linear space-np.linspace: gives same space between elements
arr=np.linspace(1,5,2)
arr

array([1., 5.])

In [ ]:
arr=np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [ ]:
#random generation function
np.random.rand(5)#gives 5 random numbers between 0 and 1

array([0.3302157 , 0.71274417, 0.23059081, 0.63223236, 0.89927723])

In [ ]:
np.random.randn(5)#case of normalization

array([ 1.65147746, -0.44231545, -0.39812322, -0.15194879, -0.04323807])

In [ ]:
np.random.randint(5)#gives any random integer between 0 and 5

1

In [ ]:
np.random.randint(10,20,10)#gives 10 random number between 10 and 20

array([12, 16, 16, 14, 19, 16, 11, 18, 15, 15], dtype=int32)

In [ ]:
#array attributes and methods
#attributes are variables defined inside a class,they cannot be called
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
#methods- they are functions defined inside a class
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
arr.sum()#gives sum of all elements

np.int64(45)

In [ ]:
#if i want the sum row wise
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [ ]:
#column wise sum
np.sum(arr,axis=0)

array([12, 15, 18])

In [ ]:
#index of maximum and minimum element
arr.argmin()


np.int64(0)

In [ ]:
arr.argmax()

np.int64(8)

In [ ]:
#to find mean
arr.mean()

np.float64(5.0)

In [ ]:
#to find standard deviation
arr.std()

np.float64(2.581988897471611)

In [ ]:
#reshape and resize
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr=arr.reshape(2,5)
arr#resize

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])